/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jessica.formulario;

import br.com.jessica.objeto.CadastrarAtestado;
import br.com.jessica.objeto.Triagem;

/**
 *
 * @author SATC
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMCadastrarPessoa = new javax.swing.JMenuItem();
        jMTriagem = new javax.swing.JMenuItem();
        jMAtestado = new javax.swing.JMenuItem();
        jMMedico = new javax.swing.JMenuItem();
        jMConsulta = new javax.swing.JMenuItem();
        jMEnfermeira = new javax.swing.JMenuItem();
        jMPaciente = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu2.setText("Cadastrar");
        jMenu2.setToolTipText("");
        jMenu2.setActionCommand("Cadastrar \nPessoa\n");

        jMCadastrarPessoa.setText("Cadastrar Pessoa");
        jMCadastrarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(jMCadastrarPessoa);

        jMTriagem.setText("Triagem");
        jMTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMTriagemActionPerformed(evt);
            }
        });
        jMenu2.add(jMTriagem);

        jMAtestado.setText("Atestado");
        jMAtestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAtestadoActionPerformed(evt);
            }
        });
        jMenu2.add(jMAtestado);

        jMMedico.setText("Mèdico");
        jMMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMMedicoActionPerformed(evt);
            }
        });
        jMenu2.add(jMMedico);

        jMConsulta.setText("Consulta");
        jMConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultaActionPerformed(evt);
            }
        });
        jMenu2.add(jMConsulta);

        jMEnfermeira.setText("Enfermeira");
        jMEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMEnfermeiraActionPerformed(evt);
            }
        });
        jMenu2.add(jMEnfermeira);

        jMPaciente.setText("Paciente");
        jMenu2.add(jMPaciente);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadastrarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarPessoaActionPerformed
        // TODO add your handling code here:
        CadastroPessoa cadastroPessoa= new CadastroPessoa();
        cadastroPessoa.setVisible(true);
    }//GEN-LAST:event_jMCadastrarPessoaActionPerformed

    private void jMTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMTriagemActionPerformed

// TODO add your handling code here:        Triagem triagem = new Triagem();
      
    }//GEN-LAST:event_jMTriagemActionPerformed

    private void jMAtestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAtestadoActionPerformed
        // TODO add your handling code here:
        Atestado atestado=new Atestado();
        atestado.setVisible(true);
        
    }//GEN-LAST:event_jMAtestadoActionPerformed

    private void jMEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMEnfermeiraActionPerformed
        // TODO add your handling code here:
        Enfermeira consultarEnfermeira=new Enfermeira();
        consultarEnfermeira.setVisible(true);
    }//GEN-LAST:event_jMEnfermeiraActionPerformed

    private void jMMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMMedicoActionPerformed
        // TODO add your handling code here:
        Medico medico=new Medico();
        medico.setVisible(true);
    }//GEN-LAST:event_jMMedicoActionPerformed

    private void jMConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultaActionPerformed
        // TODO add your handling code here:
       Consulta consulta=new Consulta();
       consulta.setVisible(true);
    }//GEN-LAST:event_jMConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMAtestado;
    private javax.swing.JMenuItem jMCadastrarPessoa;
    private javax.swing.JMenuItem jMConsulta;
    private javax.swing.JMenuItem jMEnfermeira;
    private javax.swing.JMenuItem jMMedico;
    private javax.swing.JMenuItem jMPaciente;
    private javax.swing.JMenuItem jMTriagem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
